// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$$1 from "./sections/Hero.tsx";
import * as $$$$$$$5 from "./sections/myHero.tsx";
import * as $$$$$$$2 from "./sections/ParagraphList.tsx";
import * as $$$$$$$3 from "./sections/SimpleTextList.tsx";
import * as $$$$$$$4 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "deco-sites/marvin-test/sections/Footer.tsx": $$$$$$$0,
    "deco-sites/marvin-test/sections/Hero.tsx": $$$$$$$1,
    "deco-sites/marvin-test/sections/myHero.tsx": $$$$$$$5,
    "deco-sites/marvin-test/sections/ParagraphList.tsx": $$$$$$$2,
    "deco-sites/marvin-test/sections/SimpleTextList.tsx": $$$$$$$3,
    "deco-sites/marvin-test/sections/Theme/Theme.tsx": $$$$$$$4,
  },
  "apps": {
    "deco-sites/marvin-test/apps/decohub.ts": $$$$$$$$$$$$0,
    "deco-sites/marvin-test/apps/site.ts": $$$$$$$$$$$$1,
  },
  "name": "deco-sites/marvin-test",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
